package gui_vendor;

import filehandling.DeliveryRunnerDatabase;
import filehandling.OrderDatabase;
import filehandling.VendorDatabase;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DeliveryRunner;
import model.MenuItem;
import model.Order;
import model.OrderStatus;
import model.Vendor;

public class OrderRequests extends javax.swing.JFrame {

    Vendor vendor;
    DefaultTableModel model;

    Order order = null;

    public OrderRequests() {
        initComponents();
    }

    public OrderRequests(Vendor vendor) {
        initComponents();
        model = (DefaultTableModel) table.getModel();
        this.vendor = vendor;
        showData();
        for (DeliveryRunner runner : DeliveryRunnerDatabase.getAllRunners()) {
            deliveryCombo.addItem(runner.getUsername());
        }
    }

    void showData() {
        vendor = VendorDatabase.getVendor(vendor.getUsername());

        model.getDataVector().removeAllElements();
        table.revalidate();

        for (Order order : OrderDatabase.getOrdersByVendorId(vendor.getUsername())) {
            if (order.getStatus() == OrderStatus.PENDING) {
                model.addRow(new Object[]{order.getOrderId(), order.getCustomer().getUsername(), order.getVendor().getUsername(), order.getTotal(), order.isDeliveryRequested()});

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        deliveryLabel = new javax.swing.JLabel();
        deliveryCombo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        deliveryLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        items = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 24)); // NOI18N
        jLabel1.setText("Order Requests");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Customer", "Vendor", "Total", "Delivery Required"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        deliveryLabel.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 14)); // NOI18N
        deliveryLabel.setText("Assign Delivery Runner");

        deliveryCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "please select from following" }));

        jButton1.setText("Accept");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        deliveryLabel1.setFont(new java.awt.Font("ITF Devanagari Marathi", 0, 14)); // NOI18N
        deliveryLabel1.setText("Ordered Items");

        items.setColumns(20);
        items.setRows(5);
        jScrollPane2.setViewportView(items);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(deliveryCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deliveryLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(34, 34, 34)
                            .addComponent(jButton1))
                        .addComponent(deliveryLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(452, 452, 452))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deliveryLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addComponent(deliveryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deliveryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        new VendorDashboard(vendor).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int i = table.getSelectedRow();
        if (i != -1) {
            String orderID = (String) table.getValueAt(i, 0);
            order = OrderDatabase.getOrderbyOrderID(orderID);
            items.setText("");
            for (MenuItem item : order.getItems()) {
                items.append(item.getItemName() + "\n");
            }
            if (!order.isDeliveryRequested()) {
                deliveryCombo.setEditable(false);
            }

        }

    }//GEN-LAST:event_tableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        order.setStatus(OrderStatus.ACCEPTED);
        double result = 0;

        if (order.isDeliveryRequested()) {
            if (deliveryCombo.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Please select delivery runner");
            } else {
                DeliveryRunner deliveryRunner = DeliveryRunnerDatabase.getdDeliveryRunner(deliveryCombo.getSelectedItem().toString());
                deliveryRunner.assignNewOrder(order);
                deliveryRunner.setEarnings(deliveryRunner.getEarnings() + result);

                double deliveryPrevEarn = DeliveryRunnerDatabase.getEarning(deliveryRunner.getUsername());
                DeliveryRunnerDatabase.createOrUpdateRunnerEarning(deliveryRunner.getUsername(), deliveryPrevEarn + result);
                deliveryRunner.setEarnings(deliveryPrevEarn + result);

                DeliveryRunnerDatabase.updateRunner(deliveryRunner);
               
                DeliveryRunnerDatabase.addAssignedOrder(deliveryRunner.getUsername(), order.getOrderId());

            }
        }
        double vendorEarning = order.getTotal() - result;

        OrderDatabase.updateOrder(order);
        double prevEarn = VendorDatabase.getEarning(vendor.getUsername());

        VendorDatabase.createOrUpdateVendorEarning(vendor.getUsername(), vendorEarning + prevEarn);

        this.dispose();
        new VendorDashboard(vendor).setVisible(true);
        JOptionPane.showMessageDialog(null, "Order Accepted");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderRequests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderRequests().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> deliveryCombo;
    private javax.swing.JLabel deliveryLabel;
    private javax.swing.JLabel deliveryLabel1;
    private javax.swing.JTextArea items;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
